.SILENT:

FILES = ramaplot.tcl pkgIndex.tcl
VERSION = 1.1
DIR = $(PLUGINDIR)/noarch/tcl/ramaplot$(VERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying ramaplot $(VERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(FILES) $(DIR) 
	
