.SILENT:

VMFILES = namdenergy.tcl pkgIndex.tcl
VMVERSION = 1.4
DIR = $(PLUGINDIR)/noarch/tcl/namdenergy$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying namdenergy $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
