.SILENT:

VMFILES = idatm.tcl pkgIndex.tcl
VMVERSION = 0.1
DIR = $(PLUGINDIR)/noarch/tcl/idatm$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying idatm $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 
