.SILENT:

VMFILES = viewmaster.tcl pkgIndex.tcl
VMVERSION = 2.6
DIR = $(PLUGINDIR)/noarch/tcl/viewmaster$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying viewmaster $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 


