.SILENT:

VMFILES = apbsrun.tcl pkgIndex.tcl radii.dat
VMVERSION = 1.3
DIR = $(PLUGINDIR)/noarch/tcl/apbsrun$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying apbsrun $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
