.SILENT:

VMFILES = vmdmovie.tcl pkgIndex.tcl
VMVERSION = 1.9
DIR = $(PLUGINDIR)/noarch/tcl/vmdmovie$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying vmdmovie $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
