.SILENT:

VMFILES = bendix.tcl pkgIndex.tcl doc/GUI-tips.gif  doc/Monsieur_Bendix_smaller_still.gif
VMVERSION = 1.1
DIR = $(PLUGINDIR)/noarch/tcl/bendix$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying bendix $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
