language: python
python:
    - "2.7"
    - "3.6"
install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pytest libnetcdf expat
    - source activate test-environment
    - python setup.py build
    - python setup.py install
script:
    - source activate test-environment
    - python setup.py test

