package:
    name: vmd-python
    version: "1.9.2"

source:
    git_url: https://github.com/Eigenstate/vmd-python.git
    git_tag: master

build:
    number: 1
    #preserve_egg_dir: True
    features:
        - It may actually work this time

requirements:
    build:
        - libnetcdf
        - numpy
    run:
        - libnetcdf
        - numpy

test:
    commands:
        - python setup.py test

about:
    home: https://github.com/Eigenstate/vmd-python
    license: VMD license
    summary: Loadable python module for VMD functions

