package:
    name: vmd-python
    version: "2.0.2"

source:
    git_url: https://github.com/Eigenstate/vmd-python.git
    git_tag: master

build:
    preserve_egg_dir: False
    number: 1

requirements:
    build:
        - python
        - libnetcdf 4.4.*
        - expat
        - numpy
        - tk 8.5.*
    run:
        - python
<<<<<<< HEAD
        - libnetcdf 4.4.*
=======
        - libnetcdf 4.5.*
>>>>>>> 8d168a7d93d9a55cda622c05b9f5b6c72c133a43
        - expat
        - numpy
        - tk 8.5.*

about:
    home: https://github.com/Eigenstate/vmd-python
    license: VMD license
    summary: Loadable python module for VMD functions

