package:
    name: vmd-python
    version: "1.9.3"

source:
    git_url: https://github.com/Eigenstate/vmd-python.git
    git_tag: master

build:
    preserve_egg_dir: False
    number: 1

requirements:
    build:
        - python
        - libnetcdf
        - numpy
    run:
        - python
        - libnetcdf
        - numpy

about:
    home: https://github.com/Eigenstate/vmd-python
    license: VMD license
    summary: Loadable python module for VMD functions

