package:
    name: vmd-python
    version: "2.0.0"

source:
    git_url: https://github.com/Eigenstate/vmd-python.git
    git_tag: testing

build:
    preserve_egg_dir: False
    number: 1

requirements:
    build:
        - python
        - libnetcdf
        - numpy
        - glibc >=2.19
    run:
        - python
        - libnetcdf
        - numpy
        - glibc >=2.19

about:
    home: https://github.com/Eigenstate/vmd-python
    license: VMD license
    summary: Loadable python module for VMD functions

