package:
    name: vmd-python
    version: "1.9.2"

source:
    git_url: https://github.com/Eigenstate/vmd-python.git
    git_tag: master

build:
    features:
        - it doesn't crash
        - it imports

    script: python setup.py install

requirements:
    build:
        - python >=2.7.0
        - libnetcdf >=4.3.2
        - expat >=2.1.0
        - numpy
    run:
        - numpy
        - libnetcdf >=4.3.2

about:
    home: https://github.com/Eigenstate/vmd-python
    license: VMD license
    summary: Loadable python module for VMD functions

