package:
    name: vmd-python
    version: "2.0.1"

source:
    git_url: https://github.com/Eigenstate/vmd-python.git
    git_tag: master

build:
    preserve_egg_dir: False
    number: 1

requirements:
    build:
        - python
        - libnetcdf 4.3.*
        - expat
        - numpy
    run:
        - python
        - libnetcdf 4.3.*
        - expat
        - numpy

about:
    home: https://github.com/Eigenstate/vmd-python
    license: VMD license
    summary: Loadable python module for VMD functions

