package:
    name: vmd-python
    version: "2.0.8"

source:
    git_url: https://github.com/Eigenstate/vmd-python.git
    git_tag: master

build:
    number: 0
    script: python -m pip install --no-deps --ignore-installed .
    skip: true  # [win]

requirements:
    build:
        - python
        - pip
        - perl
        - make
        - nomkl
        - libnetcdf 4.4.*
        - expat
        - numpy >=1.13
        - tk 8.5.*
    run:
        - python
        - libnetcdf 4.4.*
        - expat
        - numpy >=1.13
        - tk 8.5.*

test:
    imports:
        - vmd
        - pytest
    requires:
        - pytest
    commands:
        - py.test --pyargs vmd

about:
    home: https://github.com/Eigenstate/vmd-python
    license: VMD license
    license_file: LICENSE
    summary: "Visual Molecular Dynamics (VMD) Python bindings"
    description: |
        vmd-python is Visual Molecular Dynamics (VMD) built as a Python
        extension module, with a few useability improvements.
    doc_url: http://vmd.robinbetz.com
    dev_url: https://github.com/Eigenstate/vmd-python

