.SILENT:

VMFILES = timeline.tcl pkgIndex.tcl
VMVERSION = 2.3
DIR = $(PLUGINDIR)/noarch/tcl/timeline$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying timeline $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
