.SILENT:

VMFILES = moltoptools.tcl pkgIndex.tcl
VMVERSION = 0.1
DIR = $(PLUGINDIR)/noarch/tcl/moltoptools$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying moltoptools $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 
