.SILENT:

VMFILES = pdbtool.tcl pkgIndex.tcl
VMVERSION = 1.1
DIR = $(PLUGINDIR)/noarch/tcl/pdbtool$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying pdbtool $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
