.SILENT:

VMFILES = namdgui.tcl namdgui_tclforces.tcl pkgIndex.tcl
VMVERSION = 1.3
DIR = $(PLUGINDIR)/noarch/tcl/namdgui$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying namdgui $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
