# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded mdff 0.5 [list source [file join $dir mdff.tcl]]
package ifneeded mdff_check 0.3 [list source [file join $dir mdff_check.tcl]]
package ifneeded mdff_correlation 0.2 [list source [file join $dir mdff_correlation.tcl]]
package ifneeded mdff_map 0.2 [list source [file join $dir mdff_map.tcl]]
package ifneeded mdff_setup 0.4 "set env(MDFFDIR) [list $dir]; [list source [file join $dir mdff_setup.tcl]]"
package ifneeded mdff_sim 0.2 [list source [file join $dir mdff_sim.tcl]]
package ifneeded mdff_tmp 0.2 [list source [file join $dir mdff_tmp.tcl]]
package ifneeded mdff_gui 0.2 "set env(MDFFDIR) [list $dir]; [list source [file join $dir mdff_gui.tcl]]"
