.SILENT:

VMFILES = modal.tcl  rmsdvt-gui.tcl  rmsdvt.tcl pkgIndex.tcl 
VMVERSION = 1.0
DIR = $(PLUGINDIR)/noarch/tcl/rmsdvt$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying rmsdvt $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
