.SILENT:

VMFILES = alascan.tcl alascan_analysis.tcl fep.tcl pkgIndex.tcl
VMVERSION = 1.0
DIR = $(PLUGINDIR)/noarch/tcl/alascanfep$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying alascanfep $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
