.SILENT:

VMFILES = propka.tcl pkgIndex.tcl

VMVERSION = 1.1
DIR = $(PLUGINDIR)/noarch/tcl/propka$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying propka $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
