.SILENT:

VMFILES = stingtool.tcl pkgIndex.tcl
VMVERSION = 1.0
DIR = $(PLUGINDIR)/noarch/tcl/stingtool$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying stingtool $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
