
TCLFILES = psipred.tcl pkgIndex.tcl
PKGVERSION = 1.1
DIR = $(PLUGINDIR)/noarch/tcl/psipred$(PKGVERSION)

#
# Rules
#
bins:
win32bins:
dynlibs:
staticlibs: 
win32staticlibs: 

distrib:
	echo "Copying psipred $(PKGVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(TCLFILES) $(DIR) 

	
