.SILENT:

VMFILES = colorscalebar.tcl pkgIndex.tcl
VMVERSION = 1.4
DIR = $(PLUGINDIR)/noarch/tcl/colorscalebar$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying colorscalebar $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 
	
