.SILENT:

VMFILES = zoomseq.tcl pkgIndex.tcl
VMVERSION = 1.2
DIR = $(PLUGINDIR)/noarch/tcl/zoomseq$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying zoomseq $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
