.SILENT:

VMFILES = heatmapper.tcl pkgIndex.tcl 
VMVERSION = 1.1
DIR = $(PLUGINDIR)/noarch/tcl/heatmapper$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying heatmapper $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
