.SILENT:

VMFILES = contactmap.tcl pkgIndex.tcl
VMVERSION = 1.1
DIR = $(PLUGINDIR)/noarch/tcl/contactmap$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying contactmap $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
