.SILENT:

IMDMENUFILES = imdmenu.tcl pkgIndex.tcl
IMDMENUVERSION = 1.0
DIR = $(PLUGINDIR)/noarch/tcl/imdmenu$(IMDMENUVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying imdmenu $(IMDMENUVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp -f $(IMDMENUFILES) $(DIR) 
