.SILENT:

VMFILES = multiplot.tcl pkgIndex.tcl
VMVERSION = 1.7
DIR = $(PLUGINDIR)/noarch/tcl/multiplot$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying multiplot $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 


