
VMFILES = download_updates.tcl multiseqdialog.tcl pkgIndex.tcl scrolledframe.tcl wait_dialog.tcl

VMVERSION = 1.1
DIR = $(PLUGINDIR)/noarch/tcl/multiseqdialog$(VMVERSION)

#
# Rules
#
bins:
win32bins:
dynlibs:
staticlibs: 
win32staticlibs: 

distrib:
	echo "Copying multiseqdialog $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
