.SILENT:

VMFILES = vcr.tcl vcr_gui.tcl pkgIndex.tcl
VMVERSION = 1.8
DIR = $(PLUGINDIR)/noarch/tcl/viewchangerender$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying viewchangerender $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
