.SILENT:

VMFILES = vmddebug.tcl debugatomsel.tcl pkgIndex.tcl
VMVERSION = 1.1
DIR = $(PLUGINDIR)/noarch/tcl/vmddebug$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying vmddebug $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

