.SILENT:

COPYFILES = navigate.tcl pkgIndex.tcl
DIR = $(PLUGINDIR)/noarch/tcl/navigate1.0

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib: 
	@echo "Copying navigate 1.0 files to $(DIR)"
	mkdir -p $(DIR) 
	cp -rf $(COPYFILES) $(DIR) 
