
VMFILES = plotter.tcl pkgIndex.tcl
VMVERSION = 1.2
DIR = $(PLUGINDIR)/noarch/tcl/plotter$(VMVERSION)

#
# Rules
#
bins:
win32bins:
dynlibs:
staticlibs: 
win32staticlibs: 

distrib:
	echo "Copying plotter $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

