.SILENT:

VMFILES = chirality.tcl chirality_gui.tcl pkgIndex.tcl
VMVERSION = 1.1
DIR = $(PLUGINDIR)/noarch/tcl/chirality$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying chirality $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
