.SILENT:

VMFILES = vdna.tcl pkgIndex.tcl
VMVERSION = 2.2
DIR = $(PLUGINDIR)/noarch/tcl/vdna$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying vdna $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
