.SILENT:

VMFILES = runsqm.tcl pkgIndex.tcl
VMVERSION = 0.2
DIR = $(PLUGINDIR)/noarch/tcl/runsqm$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying runsqm $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

