.SILENT:

VMFILES = runante.tcl pkgIndex.tcl
VMVERSION = 0.2
DIR = $(PLUGINDIR)/noarch/tcl/runante$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying runante $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 
