.SILENT:

VMFILES = gofrgui.tcl pkgIndex.tcl
VMVERSION = 1.3
DIR = $(PLUGINDIR)/noarch/tcl/gofrgui$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying gofrgui $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

