.SILENT:

TKCONFILES = vmdtkcon.tcl tkcon-modified.tcl pkgIndex.tcl tkcon-2.3 README
DIR = $(PLUGINDIR)/noarch/tcl/vmdtkcon1.1

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib: 
	@echo "Copying vmdtkcon 1.1 files to $(DIR)"
	mkdir -p $(DIR) 
	cp -rf $(TKCONFILES) $(DIR) 
