.SILENT:

VMFILES = clonerep.tcl pkgIndex.tcl
VMVERSION = 1.3
DIR = $(PLUGINDIR)/noarch/tcl/clonerep$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying clonerep $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
