.SILENT:

VMFILES = aligntool.tcl cealign.tcl pkgIndex.tcl
VMVERSION = 1.0
DIR = $(PLUGINDIR)/noarch/tcl/aligntool$(VMVERSION)

bins: 
win32bins: 
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying aligntool $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
