/***************************************************************************
 *cr
 *cr            (C) Copyright 1995-2019 The Board of Trustees of the
 *cr                        University of Illinois
 *cr                         All Rights Reserved
 *cr
 ***************************************************************************/

/***************************************************************************
 * RCS INFORMATION:
 *
 *      $RCSfile: DisplayFltkMenu.h,v $
 *      $Author: johns $        $Locker:  $             $State: Exp $
 *      $Revision: 1.15 $       $Date: 2019/01/17 21:20:59 $
 *
 ***************************************************************************
 * DESCRIPTION:
 *  generated by Fast Light User Interface Designer (fluid) version 1.0011
 *
 ***************************************************************************/

#ifndef display_h
#define display_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Counter.H>
#include <FL/Fl_Box.H>
#include "VMDFltkMenu.h"

/// VMDFltkMenu subclass providing a GUI for setting display options
class DisplayFltkMenu : public VMDFltkMenu {
public:
  DisplayFltkMenu(VMDApp *);

private:
  void make_window();
  void update_settings();

  Fl_Counter *nearclip;
  Fl_Counter *farclip;
  Fl_Counter *eyesep;
  Fl_Counter *focal;
  Fl_Counter *screenh;
  Fl_Counter *screend;

  Fl_Choice  *cuemode;
  Fl_Counter *cuestart;
  Fl_Counter *cueend;
  Fl_Counter *cuedensity;

  Fl_Choice  *shadowmode;

  Fl_Choice  *aomode;
  Fl_Counter *aoambient;
  Fl_Counter *aodirect;

  Fl_Choice  *dofmode;
  Fl_Counter *doffnumber;
  Fl_Counter *doffocaldist;

protected:
  int act_on_command(int, Command *);
};
#endif
