
TCLFILES = blast.tcl blast_resultviewer.tcl pkgIndex.tcl
PKGVERSION = 1.11
DIR = $(PLUGINDIR)/noarch/tcl/blast$(PKGVERSION)

#
# Rules
#
bins:
win32bins:
dynlibs:
staticlibs: 
win32staticlibs: 

distrib:
	echo "Copying blast $(PKGVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(TCLFILES) $(DIR) 

	
