/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.13u-20020719-1411
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON
/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#                       define SWIGIMPORT(a) extern a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#                       define SWIGIMPORT(a) extern a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#                       define SWIGIMPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#                       define SWIGIMPORT(a) a
#               endif
#       endif
#else
#       define SWIGEXPORT(a) a
#       define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;                 
  swig_converter_func     converter;
  const char             *str;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
  void                   *clientdata;	
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);

#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  while (s) {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) 
{
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
     ty = (*ty->dcast)(ptr);
     if (ty) lastty = ty;
  }
  return lastty;
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
	if ((strcmp(tc->name, equiv->name) == 0))
	  SWIG_TypeClientData(tc,clientdata);
	tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}
#endif

#ifdef __cplusplus
}

#endif

/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include <stdlib.h>
#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(int)               SWIG_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGEXPORT(char *)            SWIG_PackData(char *c, void *, int);
SWIGEXPORT(char *)            SWIG_UnpackData(char *c, void *, int);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *,int own);
SWIGEXPORT(PyObject *)        SWIG_NewPackedObj(void *, int sz, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);
#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) { Py_DECREF(obj); }
      return 0;
    } else {
      if (newref) { Py_DECREF(obj); }
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) { Py_DECREF(obj); }
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }
  return 0;

type_error:
  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[1024];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (own) {
      PyObject *n = PyInt_FromLong(1);
      PyObject_SetAttrString(inst,(char*)"thisown",n);
      Py_DECREF(n);
    }
    robj = inst;
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif








/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_FILE swig_types[0] 
#define  SWIGTYPE_p_stringhash swig_types[1] 
#define  SWIGTYPE_p_topo_mol swig_types[2] 
#define  SWIGTYPE_p_topo_defs swig_types[3] 
#define  SWIGTYPE_p_topo_mol_ident_t swig_types[4] 
static swig_type_info *swig_types[6];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    init_psfgen

#define SWIG_name    "_psfgen"

#include "pdb_file_extract.h"
#include "psf_file_extract.h"
#include "topo_defs.h"
#include "topo_mol.h"
#include "topo_mol_output.h"
#include "charmm_parse_topo_defs.h"
#include "stringhash.h"
#include "extract_alias.h"

static void stdout_msg(void *v, const char *s) {
  printf("%s\n", s);
}

#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_pdb_file_extract_residues(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    FILE *arg2 ;
    stringhash *arg3 ;
    void *arg4 ;
    void (*arg5)(void *,char const *) ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj3  = 0 ;
    PyObject * obj4  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOOOO:pdb_file_extract_residues",&obj0,&obj1,&obj2,&obj3,&obj4)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_FILE,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_stringhash,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, 0, 1)) == -1) return NULL;
    {
        arg5=stdout_msg;
    }
    result = (int)pdb_file_extract_residues(arg1,arg2,arg3,arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_pdb_file_extract_coordinates(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    FILE *arg2 ;
    char *arg3 ;
    stringhash *arg4 ;
    void *arg5 ;
    void (*arg6)(void *,char const *) ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj3  = 0 ;
    PyObject * obj4  = 0 ;
    PyObject * obj5  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOsOOO:pdb_file_extract_coordinates",&obj0,&obj1,&arg3,&obj3,&obj4,&obj5)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_FILE,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, SWIGTYPE_p_stringhash,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj4,(void **) &arg5, 0, 1)) == -1) return NULL;
    {
        arg6=stdout_msg;
    }
    result = (int)pdb_file_extract_coordinates(arg1,arg2,(char const *)arg3,arg4,arg5,arg6);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_psf_file_extract(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    FILE *arg2 ;
    void *arg3 ;
    void (*arg4)(void *,char const *) ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj3  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOOO:psf_file_extract",&obj0,&obj1,&obj2,&obj3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_FILE,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, 0, 1)) == -1) return NULL;
    {
        arg4=stdout_msg;
    }
    result = (int)psf_file_extract(arg1,arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_defs_create(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *result;
    
    if(!PyArg_ParseTuple(args,(char *)":topo_defs_create")) return NULL;
    result = (topo_defs *)topo_defs_create();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_topo_defs, 0);
    return resultobj;
}


static PyObject *_wrap_topo_defs_destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:topo_defs_destroy",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    topo_defs_destroy(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_topo_defs_error_handler(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    void *arg2 ;
    void (*arg3)(void *,char const *) ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:topo_defs_error_handler",&obj0,&obj1,&obj2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, 0, 1)) == -1) return NULL;
    {
        arg3=stdout_msg;
    }
    topo_defs_error_handler(arg1,arg2,arg3);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_topo_defs_auto_angles(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    int arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:topo_defs_auto_angles",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    topo_defs_auto_angles(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_topo_defs_auto_dihedrals(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    int arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:topo_defs_auto_dihedrals",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    topo_defs_auto_dihedrals(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_topo_defs_type(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    char *arg2 ;
    double arg3 ;
    int arg4 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Osdi:topo_defs_type",&obj0,&arg2,&arg3,&arg4)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    result = (int)topo_defs_type(arg1,(char const *)arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_defs_residue(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    char *arg2 ;
    int arg3 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Osi:topo_defs_residue",&obj0,&arg2,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    result = (int)topo_defs_residue(arg1,(char const *)arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_defs_end(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:topo_defs_end",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    result = (int)topo_defs_end(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_defs_atom(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    char *arg2 ;
    int arg3 ;
    char *arg4 ;
    int arg5 ;
    int arg6 ;
    char *arg7 ;
    double arg8 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Osisiisd:topo_defs_atom",&obj0,&arg2,&arg3,&arg4,&arg5,&arg6,&arg7,&arg8)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    result = (int)topo_defs_atom(arg1,(char const *)arg2,arg3,(char const *)arg4,arg5,arg6,(char const *)arg7,arg8);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_defs_bond(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    char *arg2 ;
    int arg3 ;
    char *arg4 ;
    int arg5 ;
    int arg6 ;
    char *arg7 ;
    int arg8 ;
    int arg9 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Osisiisii:topo_defs_bond",&obj0,&arg2,&arg3,&arg4,&arg5,&arg6,&arg7,&arg8,&arg9)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    result = (int)topo_defs_bond(arg1,(char const *)arg2,arg3,(char const *)arg4,arg5,arg6,(char const *)arg7,arg8,arg9);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_defs_angle(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    char *arg2 ;
    int arg3 ;
    char *arg4 ;
    int arg5 ;
    int arg6 ;
    char *arg7 ;
    int arg8 ;
    int arg9 ;
    char *arg10 ;
    int arg11 ;
    int arg12 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Osisiisiisii:topo_defs_angle",&obj0,&arg2,&arg3,&arg4,&arg5,&arg6,&arg7,&arg8,&arg9,&arg10,&arg11,&arg12)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    result = (int)topo_defs_angle(arg1,(char const *)arg2,arg3,(char const *)arg4,arg5,arg6,(char const *)arg7,arg8,arg9,(char const *)arg10,arg11,arg12);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_defs_dihedral(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    char *arg2 ;
    int arg3 ;
    char *arg4 ;
    int arg5 ;
    int arg6 ;
    char *arg7 ;
    int arg8 ;
    int arg9 ;
    char *arg10 ;
    int arg11 ;
    int arg12 ;
    char *arg13 ;
    int arg14 ;
    int arg15 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Osisiisiisiisii:topo_defs_dihedral",&obj0,&arg2,&arg3,&arg4,&arg5,&arg6,&arg7,&arg8,&arg9,&arg10,&arg11,&arg12,&arg13,&arg14,&arg15)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    result = (int)topo_defs_dihedral(arg1,(char const *)arg2,arg3,(char const *)arg4,arg5,arg6,(char const *)arg7,arg8,arg9,(char const *)arg10,arg11,arg12,(char const *)arg13,arg14,arg15);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_defs_improper(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    char *arg2 ;
    int arg3 ;
    char *arg4 ;
    int arg5 ;
    int arg6 ;
    char *arg7 ;
    int arg8 ;
    int arg9 ;
    char *arg10 ;
    int arg11 ;
    int arg12 ;
    char *arg13 ;
    int arg14 ;
    int arg15 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Osisiisiisiisii:topo_defs_improper",&obj0,&arg2,&arg3,&arg4,&arg5,&arg6,&arg7,&arg8,&arg9,&arg10,&arg11,&arg12,&arg13,&arg14,&arg15)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    result = (int)topo_defs_improper(arg1,(char const *)arg2,arg3,(char const *)arg4,arg5,arg6,(char const *)arg7,arg8,arg9,(char const *)arg10,arg11,arg12,(char const *)arg13,arg14,arg15);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_defs_conformation(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    char *arg2 ;
    int arg3 ;
    char *arg4 ;
    int arg5 ;
    int arg6 ;
    char *arg7 ;
    int arg8 ;
    int arg9 ;
    char *arg10 ;
    int arg11 ;
    int arg12 ;
    char *arg13 ;
    int arg14 ;
    int arg15 ;
    double arg16 ;
    double arg17 ;
    double arg18 ;
    int arg19 ;
    double arg20 ;
    double arg21 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Osisiisiisiisiidddidd:topo_defs_conformation",&obj0,&arg2,&arg3,&arg4,&arg5,&arg6,&arg7,&arg8,&arg9,&arg10,&arg11,&arg12,&arg13,&arg14,&arg15,&arg16,&arg17,&arg18,&arg19,&arg20,&arg21)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    result = (int)topo_defs_conformation(arg1,(char const *)arg2,arg3,(char const *)arg4,arg5,arg6,(char const *)arg7,arg8,arg9,(char const *)arg10,arg11,arg12,(char const *)arg13,arg14,arg15,arg16,arg17,arg18,arg19,arg20,arg21);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_defs_default_patching_first(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    char *arg2 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:topo_defs_default_patching_first",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    result = (int)topo_defs_default_patching_first(arg1,(char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_defs_default_patching_last(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    char *arg2 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:topo_defs_default_patching_last",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    result = (int)topo_defs_default_patching_last(arg1,(char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_defs_patching_first(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    char *arg2 ;
    char *arg3 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oss:topo_defs_patching_first",&obj0,&arg2,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    result = (int)topo_defs_patching_first(arg1,(char const *)arg2,(char const *)arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_defs_patching_last(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    char *arg2 ;
    char *arg3 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oss:topo_defs_patching_last",&obj0,&arg2,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    result = (int)topo_defs_patching_last(arg1,(char const *)arg2,(char const *)arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_mol_create(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    topo_mol *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:topo_mol_create",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    result = (topo_mol *)topo_mol_create(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_topo_mol, 0);
    return resultobj;
}


static PyObject *_wrap_topo_mol_destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:topo_mol_destroy",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    topo_mol_destroy(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_topo_mol_error_handler(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    void *arg2 ;
    void (*arg3)(void *,char const *) ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:topo_mol_error_handler",&obj0,&obj1,&obj2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, 0, 1)) == -1) return NULL;
    {
        arg3=stdout_msg;
    }
    topo_mol_error_handler(arg1,arg2,arg3);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_topo_mol_segment(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    char *arg2 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:topo_mol_segment",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    result = (int)topo_mol_segment(arg1,(char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_mol_segment_first(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    char *arg2 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:topo_mol_segment_first",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    result = (int)topo_mol_segment_first(arg1,(char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_mol_segment_last(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    char *arg2 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:topo_mol_segment_last",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    result = (int)topo_mol_segment_last(arg1,(char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_mol_segment_auto_angles(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    int arg2 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:topo_mol_segment_auto_angles",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    result = (int)topo_mol_segment_auto_angles(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_mol_segment_auto_dihedrals(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    int arg2 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:topo_mol_segment_auto_dihedrals",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    result = (int)topo_mol_segment_auto_dihedrals(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_mol_residue(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    char *arg2 ;
    char *arg3 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oss:topo_mol_residue",&obj0,&arg2,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    result = (int)topo_mol_residue(arg1,(char const *)arg2,(char const *)arg3,"");
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_mol_mutate(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    char *arg2 ;
    char *arg3 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oss:topo_mol_mutate",&obj0,&arg2,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    result = (int)topo_mol_mutate(arg1,(char const *)arg2,(char const *)arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_mol_end(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:topo_mol_end",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    result = (int)topo_mol_end(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_mol_ident_t_segid_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol_ident_t *arg1 ;
    char *arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:topo_mol_ident_t_segid_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol_ident_t,1)) == -1) return NULL;
    {
        arg1->segid = (char const *) malloc(strlen(arg2)+1);
        strcpy((char*)arg1->segid,arg2);
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_topo_mol_ident_t_segid_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol_ident_t *arg1 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:topo_mol_ident_t_segid_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol_ident_t,1)) == -1) return NULL;
    result = (char *) (arg1->segid);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_topo_mol_ident_t_resid_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol_ident_t *arg1 ;
    char *arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:topo_mol_ident_t_resid_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol_ident_t,1)) == -1) return NULL;
    {
        arg1->resid = (char const *) malloc(strlen(arg2)+1);
        strcpy((char*)arg1->resid,arg2);
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_topo_mol_ident_t_resid_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol_ident_t *arg1 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:topo_mol_ident_t_resid_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol_ident_t,1)) == -1) return NULL;
    result = (char *) (arg1->resid);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_topo_mol_ident_t_aname_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol_ident_t *arg1 ;
    char *arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:topo_mol_ident_t_aname_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol_ident_t,1)) == -1) return NULL;
    {
        arg1->aname = (char const *) malloc(strlen(arg2)+1);
        strcpy((char*)arg1->aname,arg2);
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_topo_mol_ident_t_aname_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol_ident_t *arg1 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:topo_mol_ident_t_aname_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol_ident_t,1)) == -1) return NULL;
    result = (char *) (arg1->aname);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_new_topo_mol_ident_t(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol_ident_t *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_topo_mol_ident_t")) return NULL;
    result = (topo_mol_ident_t *)(topo_mol_ident_t *) calloc(1, sizeof(topo_mol_ident_t));
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_topo_mol_ident_t, 0);
    return resultobj;
}


static PyObject *_wrap_delete_topo_mol_ident_t(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol_ident_t *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_topo_mol_ident_t",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol_ident_t,1)) == -1) return NULL;
    free((char *) arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_topo_mol_patch(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    topo_mol_ident_t *arg2 ;
    int arg3 ;
    char *arg4 ;
    int arg5 ;
    int arg6 ;
    int arg7 ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOsiii:topo_mol_patch",&obj0,&obj1,&arg4,&arg5,&arg6,&arg7)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    {
        int i;
        if (!PyList_Check(obj1)) {
            PyErr_SetString(PyExc_ValueError, "Expected a list of ident_t.");
            return NULL;
        }
        arg3 = PyList_Size(obj1);
        arg2 = (topo_mol_ident_t *)malloc(arg3*sizeof(topo_mol_ident_t));
        for (i=0; i<arg3; i++) {
            PyObject *anameobj;
            PyObject *identobj = PyList_GET_ITEM(obj1, i);
            if (!PyDict_Check(identobj)) {
                free(arg2);
                PyErr_SetString(PyExc_ValueError, "Expected a list of dictionaries.");
                return NULL;
            }
            arg2[i].segid = PyString_AsString(PyDict_GetItemString(identobj, "segid"));
            arg2[i].resid = PyString_AsString(PyDict_GetItemString(identobj, "resid"));
            if ((anameobj = PyDict_GetItemString(identobj, "aname"))) {
                arg2[i].aname = PyString_AsString(anameobj);
            }else {
                arg2[i].aname = 0;
            }
        }
    }
    result = (int)topo_mol_patch(arg1,(topo_mol_ident_t const *)arg2,arg3,(char const *)arg4,arg5,arg6,arg7);
    
    resultobj = PyInt_FromLong((long)result);
    {
        free(arg2);
    }
    return resultobj;
}


static PyObject *_wrap_topo_mol_regenerate_angles(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:topo_mol_regenerate_angles",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    result = (int)topo_mol_regenerate_angles(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_mol_regenerate_dihedrals(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:topo_mol_regenerate_dihedrals",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    result = (int)topo_mol_regenerate_dihedrals(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_mol_delete_atom(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    topo_mol_ident_t *arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:topo_mol_delete_atom",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    {
        PyObject *tmpobj;
        if (!PyDict_Check(obj1)) {
            PyErr_SetString(PyExc_ValueError, "Expected a dictionary.");
            return NULL;
        }
        arg2 = (topo_mol_ident_t *)malloc(sizeof(topo_mol_ident_t));
        tmpobj = PyDict_GetItemString(obj1, "segid");
        arg2->segid = tmpobj ? PyString_AsString(tmpobj) : 0;
        tmpobj = PyDict_GetItemString(obj1, "resid");
        arg2->resid = tmpobj ? PyString_AsString(tmpobj) : 0;
        tmpobj = PyDict_GetItemString(obj1, "aname");
        arg2->aname = tmpobj ? PyString_AsString(tmpobj) : 0;
    }
    topo_mol_delete_atom(arg1,(topo_mol_ident_t const *)arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        free(arg2);
    }
    return resultobj;
}


static PyObject *_wrap_topo_mol_multiply_atoms(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    topo_mol_ident_t *arg2 ;
    int arg3 ;
    int arg4 ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOi:topo_mol_multiply_atoms",&obj0,&obj1,&arg4)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    {
        int i;
        if (!PyList_Check(obj1)) {
            PyErr_SetString(PyExc_ValueError, "Expected a list of ident_t.");
            return NULL;
        }
        arg3 = PyList_Size(obj1);
        arg2 = (topo_mol_ident_t *)malloc(arg3*sizeof(topo_mol_ident_t));
        for (i=0; i<arg3; i++) {
            PyObject *anameobj;
            PyObject *identobj = PyList_GET_ITEM(obj1, i);
            if (!PyDict_Check(identobj)) {
                free(arg2);
                PyErr_SetString(PyExc_ValueError, "Expected a list of dictionaries.");
                return NULL;
            }
            arg2[i].segid = PyString_AsString(PyDict_GetItemString(identobj, "segid"));
            arg2[i].resid = PyString_AsString(PyDict_GetItemString(identobj, "resid"));
            if ((anameobj = PyDict_GetItemString(identobj, "aname"))) {
                arg2[i].aname = PyString_AsString(anameobj);
            }else {
                arg2[i].aname = 0;
            }
        }
    }
    result = (int)topo_mol_multiply_atoms(arg1,(topo_mol_ident_t const *)arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    {
        free(arg2);
    }
    return resultobj;
}


static PyObject *_wrap_topo_mol_set_xyz(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    topo_mol_ident_t *arg2 ;
    double arg3 ;
    double arg4 ;
    double arg5 ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOddd:topo_mol_set_xyz",&obj0,&obj1,&arg3,&arg4,&arg5)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    {
        PyObject *tmpobj;
        if (!PyDict_Check(obj1)) {
            PyErr_SetString(PyExc_ValueError, "Expected a dictionary.");
            return NULL;
        }
        arg2 = (topo_mol_ident_t *)malloc(sizeof(topo_mol_ident_t));
        tmpobj = PyDict_GetItemString(obj1, "segid");
        arg2->segid = tmpobj ? PyString_AsString(tmpobj) : 0;
        tmpobj = PyDict_GetItemString(obj1, "resid");
        arg2->resid = tmpobj ? PyString_AsString(tmpobj) : 0;
        tmpobj = PyDict_GetItemString(obj1, "aname");
        arg2->aname = tmpobj ? PyString_AsString(tmpobj) : 0;
    }
    result = (int)topo_mol_set_xyz(arg1,(topo_mol_ident_t const *)arg2,arg3,arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    {
        free(arg2);
    }
    return resultobj;
}


static PyObject *_wrap_topo_mol_clear_xyz(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    topo_mol_ident_t *arg2 ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:topo_mol_clear_xyz",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    {
        PyObject *tmpobj;
        if (!PyDict_Check(obj1)) {
            PyErr_SetString(PyExc_ValueError, "Expected a dictionary.");
            return NULL;
        }
        arg2 = (topo_mol_ident_t *)malloc(sizeof(topo_mol_ident_t));
        tmpobj = PyDict_GetItemString(obj1, "segid");
        arg2->segid = tmpobj ? PyString_AsString(tmpobj) : 0;
        tmpobj = PyDict_GetItemString(obj1, "resid");
        arg2->resid = tmpobj ? PyString_AsString(tmpobj) : 0;
        tmpobj = PyDict_GetItemString(obj1, "aname");
        arg2->aname = tmpobj ? PyString_AsString(tmpobj) : 0;
    }
    result = (int)topo_mol_clear_xyz(arg1,(topo_mol_ident_t const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    {
        free(arg2);
    }
    return resultobj;
}


static PyObject *_wrap_topo_mol_guess_xyz(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:topo_mol_guess_xyz",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    result = (int)topo_mol_guess_xyz(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_mol_write_pdb(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    FILE *arg2 ;
    void *arg3 ;
    void (*arg4)(void *,char const *) ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj3  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOOO:topo_mol_write_pdb",&obj0,&obj1,&obj2,&obj3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_FILE,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, 0, 1)) == -1) return NULL;
    {
        arg4=stdout_msg;
    }
    result = (int)topo_mol_write_pdb(arg1,arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_topo_mol_write_psf(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_mol *arg1 ;
    FILE *arg2 ;
    int arg3 ;
    void *arg4 ;
    void (*arg5)(void *,char const *) ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj3  = 0 ;
    PyObject * obj4  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOiOO:topo_mol_write_psf",&obj0,&obj1,&arg3,&obj3,&obj4)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_mol,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_FILE,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj3,(void **) &arg4, 0, 1)) == -1) return NULL;
    {
        arg5=stdout_msg;
    }
    result = (int)topo_mol_write_psf(arg1,arg2,arg3,arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_charmm_parse_topo_defs(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    topo_defs *arg1 ;
    FILE *arg2 ;
    void *arg3 ;
    void (*arg4)(void *,char const *) ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj3  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOOO:charmm_parse_topo_defs",&obj0,&obj1,&obj2,&obj3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_topo_defs,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_FILE,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, 0, 1)) == -1) return NULL;
    {
        arg4=stdout_msg;
    }
    result = (int)charmm_parse_topo_defs(arg1,arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_stringhash_create(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stringhash *result;
    
    if(!PyArg_ParseTuple(args,(char *)":stringhash_create")) return NULL;
    result = (stringhash *)stringhash_create();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_stringhash, 0);
    return resultobj;
}


static PyObject *_wrap_stringhash_destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stringhash *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:stringhash_destroy",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_stringhash,1)) == -1) return NULL;
    stringhash_destroy(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_stringhash_insert(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stringhash *arg1 ;
    char *arg2 ;
    char *arg3 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oss:stringhash_insert",&obj0,&arg2,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_stringhash,1)) == -1) return NULL;
    result = (char *)stringhash_insert(arg1,(char const *)arg2,(char const *)arg3);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_stringhash_lookup(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stringhash *arg1 ;
    char *arg2 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:stringhash_lookup",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_stringhash,1)) == -1) return NULL;
    result = (char *)stringhash_lookup(arg1,(char const *)arg2);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_stringhash_delete(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stringhash *arg1 ;
    char *arg2 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:stringhash_delete",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_stringhash,1)) == -1) return NULL;
    result = (char *)stringhash_delete(arg1,(char const *)arg2);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_extract_alias_residue_define(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stringhash *arg1 ;
    char *arg2 ;
    char *arg3 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oss:extract_alias_residue_define",&obj0,&arg2,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_stringhash,1)) == -1) return NULL;
    result = (int)extract_alias_residue_define(arg1,(char const *)arg2,(char const *)arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_extract_alias_atom_define(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stringhash *arg1 ;
    char *arg2 ;
    char *arg3 ;
    char *arg4 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Osss:extract_alias_atom_define",&obj0,&arg2,&arg3,&arg4)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_stringhash,1)) == -1) return NULL;
    result = (int)extract_alias_atom_define(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_extract_alias_residue_check(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stringhash *arg1 ;
    char *arg2 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:extract_alias_residue_check",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_stringhash,1)) == -1) return NULL;
    result = (char *)extract_alias_residue_check(arg1,(char const *)arg2);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_extract_alias_atom_check(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    stringhash *arg1 ;
    char *arg2 ;
    char *arg3 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oss:extract_alias_atom_check",&obj0,&arg2,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_stringhash,1)) == -1) return NULL;
    result = (char *)extract_alias_atom_check(arg1,(char const *)arg2,(char const *)arg3);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_fopen(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    char *arg2 ;
    FILE *result;
    
    if(!PyArg_ParseTuple(args,(char *)"ss:fopen",&arg1,&arg2)) return NULL;
    result = (FILE *)fopen((char const *)arg1,(char const *)arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_FILE, 0);
    return resultobj;
}


static PyObject *_wrap_fclose(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    FILE *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:fclose",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_FILE,1)) == -1) return NULL;
    result = (int)fclose(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyMethodDef SwigMethods[] = {
	 { (char *)"pdb_file_extract_residues", _wrap_pdb_file_extract_residues, METH_VARARGS },
	 { (char *)"pdb_file_extract_coordinates", _wrap_pdb_file_extract_coordinates, METH_VARARGS },
	 { (char *)"psf_file_extract", _wrap_psf_file_extract, METH_VARARGS },
	 { (char *)"topo_defs_create", _wrap_topo_defs_create, METH_VARARGS },
	 { (char *)"topo_defs_destroy", _wrap_topo_defs_destroy, METH_VARARGS },
	 { (char *)"topo_defs_error_handler", _wrap_topo_defs_error_handler, METH_VARARGS },
	 { (char *)"topo_defs_auto_angles", _wrap_topo_defs_auto_angles, METH_VARARGS },
	 { (char *)"topo_defs_auto_dihedrals", _wrap_topo_defs_auto_dihedrals, METH_VARARGS },
	 { (char *)"topo_defs_type", _wrap_topo_defs_type, METH_VARARGS },
	 { (char *)"topo_defs_residue", _wrap_topo_defs_residue, METH_VARARGS },
	 { (char *)"topo_defs_end", _wrap_topo_defs_end, METH_VARARGS },
	 { (char *)"topo_defs_atom", _wrap_topo_defs_atom, METH_VARARGS },
	 { (char *)"topo_defs_bond", _wrap_topo_defs_bond, METH_VARARGS },
	 { (char *)"topo_defs_angle", _wrap_topo_defs_angle, METH_VARARGS },
	 { (char *)"topo_defs_dihedral", _wrap_topo_defs_dihedral, METH_VARARGS },
	 { (char *)"topo_defs_improper", _wrap_topo_defs_improper, METH_VARARGS },
	 { (char *)"topo_defs_conformation", _wrap_topo_defs_conformation, METH_VARARGS },
	 { (char *)"topo_defs_default_patching_first", _wrap_topo_defs_default_patching_first, METH_VARARGS },
	 { (char *)"topo_defs_default_patching_last", _wrap_topo_defs_default_patching_last, METH_VARARGS },
	 { (char *)"topo_defs_patching_first", _wrap_topo_defs_patching_first, METH_VARARGS },
	 { (char *)"topo_defs_patching_last", _wrap_topo_defs_patching_last, METH_VARARGS },
	 { (char *)"topo_mol_create", _wrap_topo_mol_create, METH_VARARGS },
	 { (char *)"topo_mol_destroy", _wrap_topo_mol_destroy, METH_VARARGS },
	 { (char *)"topo_mol_error_handler", _wrap_topo_mol_error_handler, METH_VARARGS },
	 { (char *)"topo_mol_segment", _wrap_topo_mol_segment, METH_VARARGS },
	 { (char *)"topo_mol_segment_first", _wrap_topo_mol_segment_first, METH_VARARGS },
	 { (char *)"topo_mol_segment_last", _wrap_topo_mol_segment_last, METH_VARARGS },
	 { (char *)"topo_mol_segment_auto_angles", _wrap_topo_mol_segment_auto_angles, METH_VARARGS },
	 { (char *)"topo_mol_segment_auto_dihedrals", _wrap_topo_mol_segment_auto_dihedrals, METH_VARARGS },
	 { (char *)"topo_mol_residue", _wrap_topo_mol_residue, METH_VARARGS },
	 { (char *)"topo_mol_mutate", _wrap_topo_mol_mutate, METH_VARARGS },
	 { (char *)"topo_mol_end", _wrap_topo_mol_end, METH_VARARGS },
	 { (char *)"topo_mol_ident_t_segid_set", _wrap_topo_mol_ident_t_segid_set, METH_VARARGS },
	 { (char *)"topo_mol_ident_t_segid_get", _wrap_topo_mol_ident_t_segid_get, METH_VARARGS },
	 { (char *)"topo_mol_ident_t_resid_set", _wrap_topo_mol_ident_t_resid_set, METH_VARARGS },
	 { (char *)"topo_mol_ident_t_resid_get", _wrap_topo_mol_ident_t_resid_get, METH_VARARGS },
	 { (char *)"topo_mol_ident_t_aname_set", _wrap_topo_mol_ident_t_aname_set, METH_VARARGS },
	 { (char *)"topo_mol_ident_t_aname_get", _wrap_topo_mol_ident_t_aname_get, METH_VARARGS },
	 { (char *)"new_topo_mol_ident_t", _wrap_new_topo_mol_ident_t, METH_VARARGS },
	 { (char *)"delete_topo_mol_ident_t", _wrap_delete_topo_mol_ident_t, METH_VARARGS },
	 { (char *)"topo_mol_patch", _wrap_topo_mol_patch, METH_VARARGS },
	 { (char *)"topo_mol_regenerate_angles", _wrap_topo_mol_regenerate_angles, METH_VARARGS },
	 { (char *)"topo_mol_regenerate_dihedrals", _wrap_topo_mol_regenerate_dihedrals, METH_VARARGS },
	 { (char *)"topo_mol_delete_atom", _wrap_topo_mol_delete_atom, METH_VARARGS },
	 { (char *)"topo_mol_multiply_atoms", _wrap_topo_mol_multiply_atoms, METH_VARARGS },
	 { (char *)"topo_mol_set_xyz", _wrap_topo_mol_set_xyz, METH_VARARGS },
	 { (char *)"topo_mol_clear_xyz", _wrap_topo_mol_clear_xyz, METH_VARARGS },
	 { (char *)"topo_mol_guess_xyz", _wrap_topo_mol_guess_xyz, METH_VARARGS },
	 { (char *)"topo_mol_write_pdb", _wrap_topo_mol_write_pdb, METH_VARARGS },
	 { (char *)"topo_mol_write_psf", _wrap_topo_mol_write_psf, METH_VARARGS },
	 { (char *)"charmm_parse_topo_defs", _wrap_charmm_parse_topo_defs, METH_VARARGS },
	 { (char *)"stringhash_create", _wrap_stringhash_create, METH_VARARGS },
	 { (char *)"stringhash_destroy", _wrap_stringhash_destroy, METH_VARARGS },
	 { (char *)"stringhash_insert", _wrap_stringhash_insert, METH_VARARGS },
	 { (char *)"stringhash_lookup", _wrap_stringhash_lookup, METH_VARARGS },
	 { (char *)"stringhash_delete", _wrap_stringhash_delete, METH_VARARGS },
	 { (char *)"extract_alias_residue_define", _wrap_extract_alias_residue_define, METH_VARARGS },
	 { (char *)"extract_alias_atom_define", _wrap_extract_alias_atom_define, METH_VARARGS },
	 { (char *)"extract_alias_residue_check", _wrap_extract_alias_residue_check, METH_VARARGS },
	 { (char *)"extract_alias_atom_check", _wrap_extract_alias_atom_check, METH_VARARGS },
	 { (char *)"fopen", _wrap_fopen, METH_VARARGS },
	 { (char *)"fclose", _wrap_fclose, METH_VARARGS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_FILE[] = {{"_p_FILE", 0, "FILE *"},{"_p_FILE"},{0}};
static swig_type_info _swigt__p_stringhash[] = {{"_p_stringhash", 0, "stringhash *"},{"_p_stringhash"},{0}};
static swig_type_info _swigt__p_topo_mol[] = {{"_p_topo_mol", 0, "topo_mol *"},{"_p_topo_mol"},{0}};
static swig_type_info _swigt__p_topo_defs[] = {{"_p_topo_defs", 0, "topo_defs *"},{"_p_topo_defs"},{0}};
static swig_type_info _swigt__p_topo_mol_ident_t[] = {{"_p_topo_mol_ident_t", 0, "topo_mol_ident_t *"},{"_p_topo_mol_ident_t"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_FILE, 
_swigt__p_stringhash, 
_swigt__p_topo_mol, 
_swigt__p_topo_defs, 
_swigt__p_topo_mol_ident_t, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{ SWIG_PY_INT,     (char *)"STRINGHASH_FAIL", (long) 0, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"EXTRACT_ALIAS_FAIL", (long) -1, 0, 0, 0},
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
}

