.SILENT:

VMFILES = exectool.tcl jobmanager.tcl pkgIndex.tcl
VMVERSION = 1.2
DIR = $(PLUGINDIR)/noarch/tcl/exectool$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying exectool $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
