.SILENT:

VMFILES = rmsdtt.tcl pkgIndex.tcl
VMVERSION = 3.0
DIR = $(PLUGINDIR)/noarch/tcl/rmsdtt$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying rmsdtt $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
