.SILENT:

VMFILES = remote.tcl pkgIndex.tcl 
VMVERSION = 0.6
DIR = $(PLUGINDIR)/noarch/tcl/remote$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying remote $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
