.SILENT:

COPYFILES = volmapgui.tcl pkgIndex.tcl
DIR = $(PLUGINDIR)/noarch/tcl/volmapgui1.1

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib: 
	@echo "Copying volmapgui 1.1 files to $(DIR)"
	mkdir -p $(DIR) 
	cp -rf $(COPYFILES) $(DIR) 
