.SILENT:

VMFILES = biocore.tcl biocorechat.tcl biocorelogin.tcl biocorepubsync.tcl pkgIndex.tcl locked.gif unlocked.gif biocoreHelper.tcl biocoreutil.tcl

VMVERSION = 1.1
DIR = $(PLUGINDIR)/noarch/tcl/biocore$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying biocore $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
