.SILENT:

VMFILES = irspecgui.tcl pkgIndex.tcl
VMVERSION = 1.3
DIR = $(PLUGINDIR)/noarch/tcl/irspecgui$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying irspecgui $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

