.SILENT:

VMFILES = namdplot.tcl pkgIndex.tcl
VMVERSION = 1.2
DIR = $(PLUGINDIR)/noarch/tcl/namdplot$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying namdplot $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 
	
